### ISSUE TITLE
Documentation for errors

### ISSUE THREAD

**Issue by arkgil** [esl/jerboa#12]
`Jerboa.Format.decode/1` returns various errors wrapped in a `{:error, _}` tuple, and `Jerboa.Format.decode!/1` raises them. However these errors are not documented, so the only way to know what is wrong is to either read an error message or name of exception struct.

It would be nice to have each of errors documented, when they are raised etc. In addition we could improve typespecs of functions which may return those errors.

@Dzol @michalwski thoughts?

**Comment by Dzol** [comment]
Since we're making them part of the public API we should document them.

I prefer documentation over a exception messages personally. For me, we use Elixir's exceptions because they're a nice way to capture information about what went wrong, instead of an `{:error, reason}` tuple. E.g. the binary that cause decoding to fail.

Then again, the exception messages are nice because STUN Error attributes can include a helpful string, so this is where that string can originate from.

**Comment by Dzol** [comment]
We should establish best practices for the exception message strings. I.e. things to make them clear and concise.

**Comment by Dzol** [comment]
See references.
