### ISSUE TITLE
Rename Jerboa.Format struct

### ISSUE THREAD

**Issue by arkgil** [esl/jerboa#13]
Currently `%Jerboa.Format{}` is a struct which carries information about decoded or not-yet-encoded STUN message. However its name does not represent its meaning.

@Dzol @michalwski any ideas?

**Comment by Dzol** [comment]
My suggestion is to move it to another module and call it `Jerboa.Parameters{}`. For the time-being at least, it's helpful to have all the information in one structure because of the complexity of encoding and decoding some STUN attributes.

E.g. the XORMappedAddress attribute requires the transaction identifier from the STUN header.

The downside of `Parameters` is that it seems to be quite a general name. Then again: the structure is quite broad in terms of what it captures.

**Comment by Dzol** [comment]
Resolved by PR #28.
