### ISSUE TITLE
Implement an easy way to find out that the message integrity was verified

### ISSUE THREAD

**Issue by arkgil** [esl/jerboa#81]
There are issues with server side processing of decoded messages, especially of current design of how verifying message integrity works. Currently there are three cases of decoding messages with MI:

1. STUN message doesn't have message integrity attribute - in this case decoding will always pass and there is no way to know if we actually verified it or not
2. STUN message has message integrity attribute, but required values (username, realm and secret) aren't in the message or aren't provided in options list - in this case decoding will fail
> note: secret can only be provided in options list
3. STUN message has message integrity; username, realm and secret are in the message or were provided in the options list but message integrity was invalid - again, decoding fails
> there are actually 4 cases, the last one is when message integrity is  successfully verified

This all works well with client side code, because TURN client doesn't require the server to include message integrity - we just pass the secret every time, and if there is a message integrity, we try to verify it.

On the server side we would like to know if the message was verified after decoding it. Right now there is no way to know if decoded message was verified. My proposal it add `:verified?` field to `Jerboa.Params` struct.

In the first of mentioned situations, this field would be set to false, because there is nothing to verify - the request wasn't autenticated.
In the second example the decoding should succeed, but the field will be set to false again.
In the third case we could also let the decoding pass and set this flag to false.

/cc @rslota @mentels

**Comment by rslota** [comment]
IMHO the `:verified?` method is better but not enough. It would for sure allow me (as server side dev) to provide implementation that behaves correctly in success cases. But all cases that lead to message being rejected would still be handled in the wrong way. 

According to the RFC in all those cases when message is not properly authenticated due to whatever reason, the server `MUST` respond to the client with 401 error code (if this is a request, not indication). This would be impossible since the message wouldn't be even decoded, so there is not way to send the response (transaction id is not accessible to server if the message is not decoded). 

Due to that, my proposal is to provide `:verify` method that will execute verification on demand and return detailed result of this verification. 

If making `:verified?` method is much, much easier we may do that as the first step to allow for, at least, secure implementation of the sever and then focus on the way of making this fully RFC compliant.

**Comment by rslota** [comment]
The described method feels sufficient. 

As long the message decoding always succeeds and there is a way of knowing about verification status afterwards, I can't see cases when this would be a problem on server side.

**Comment by arkgil** [comment]
Great. I'll take care of that.

**Comment by rslota** [comment]
There is actually one more thing. According to RFC:
```
If the message contains a MESSAGE-INTEGRITY attribute, but is
      missing the USERNAME, REALM, or NONCE attribute, the server MUST
      generate an error response with an error code of 400 (Bad
      Request).  This response SHOULD NOT include a USERNAME, NONCE,
      REALM, or MESSAGE-INTEGRITY attribute.
```

As you can see, it's important for server to know exactly what went wrong while decoding. In this case sever needs to know that there was indeed `mesage-integrity` included for this message in order to know that it needs to respond with `400` error code, not `401`.

**Comment by arkgil** [comment]
How about adding `:signed?` field in the Params struct, which will be set to true if there was message integrity in the message. Relevant attribtues can be retrieved using `Params.get_attr` if necessary.

**Comment by rslota** [comment]
That would be great. I think `:signed?` and `:verified?` cover all cases.
